// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.ufscar.dsw.agenda.domain;

import br.com.ufscar.dsw.agenda.domain.Contato;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Contato_Roo_Configurable {
    
    declare @type: Contato: @Configurable;
    
}
